# Generated by Django 5.1 on 2024-08-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_articlescope_article_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной раздел'),
        ),
    ]
